global using System;
global using System.Collections.Generic;
global using Nazar.Components;
global using Nazar.Initialization;
global using Nazar.Messaging.Systems;
global using Nazar.Rendering.Components;
global using Nazar.Rendering.Systems;
global using Nazar.Systems;
global using DefaultEcs;
global using DefaultEcs.System;
global using Nazar.Components;
global using Nazar.Rendering.Components;
global using StereoKit;
global using World = DefaultEcs.World;
global using StereoKit.Framework;